export const mockData = [
  {
    field_max_length: '50|null|null|null|null|null',
    field_name: 'Name|Address|Occupation|Age|Location|Gender',
    field_type: 'textField|textField|textField|inputNumber|date|dropdown',
    field_min_length: '3|null|null|null|null|null',
    event_id: 2,
    updated_at: '2023-06-22T10:46:42',
    id: 6,
    field_validation: '0|1|1|undefined|1|1',
    status: true,
    created_at: '2023-06-22T10:46:42',
  },
  {
    field_max_length: '50|null|null|null|null|null',
    field_name: 'Name|Address|Occupation|Age|Location|Gender',
    field_type: 'textField|textField|textField|inputNumber|date|dropdown',
    field_min_length: '3|null|null|null|null|null',
    event_id: 2,
    updated_at: '2023-06-22T10:47:06',
    id: 7,
    field_validation: '0|1|1|undefined|1|1',
    status: true,
    created_at: '2023-06-22T10:47:06',
  },
];
